// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6rjHGfvS90eIjtO-7XHR-QaLy-v3B5M0',
    appId: '1:487312313827:web:42bfb29106e3411a9d24d6',
    messagingSenderId: '487312313827',
    projectId: 'flutterapp2-e8f46',
    authDomain: 'flutterapp2-e8f46.firebaseapp.com',
    storageBucket: 'flutterapp2-e8f46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkETnu7LxmT7BR3DS912sXIhddk31nyrk',
    appId: '1:487312313827:ios:d90af8264ef41e799d24d6',
    messagingSenderId: '487312313827',
    projectId: 'flutterapp2-e8f46',
    storageBucket: 'flutterapp2-e8f46.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkETnu7LxmT7BR3DS912sXIhddk31nyrk',
    appId: '1:487312313827:ios:d90af8264ef41e799d24d6',
    messagingSenderId: '487312313827',
    projectId: 'flutterapp2-e8f46',
    storageBucket: 'flutterapp2-e8f46.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
